CREATE SEQUENCE if not exists s START WITH 100 INCREMENT BY 10;
CREATE SEQUENCE if not exists s2 START WITH -100 INCREMENT BY -10;
CREATE SEQUENCE if not exists s3 START WITH -100 INCREMENT BY 10 MINVALUE -100 MAXVALUE 1000;


select NEXTVAL('s');
select NEXTVAL('s');
select NEXTVAL('s');